sudo: required
services:
    - docker

before_install:
    - docker build -t ankitkr24/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ankitkr24/react-test npm test

after_success:
    - docker build -t ankitkr24/multi-client ./client
    - docker build -t ankitkr24/multi-nginx ./nginx
    - docker build -t ankitkr24/multi-server ./server
    - docker build -t ankitkr24/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push to Docker Hub
    - docker push ankitkr24/multi-client
    - docker push ankitkr24/multi-nginx
    - docker push ankitkr24/multi-server
    - docker push ankitkr24/multi-worker

    