version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        env_file:
            - ./.env
        depends_on:
            - postgres
    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
        env_file:
            - ./.env
    nginx:
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        restart: always
        ports:
            - '3050:80'
        depends_on:
            - api
            - client
